version: 0.0
os: linux

files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/deployment-archive

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ec2-user



